CREATE SCHEMA testdb AUTHORIZATION DBA;

-- Set default schema to 'testdb'
SET SCHEMA testdb;

-- Script to create the 'user' table
CREATE TABLE user (
                      uuid CHAR(36) PRIMARY KEY,
                      email VARCHAR(255),
                      created TIMESTAMP,
                      modified TIMESTAMP,
                      is_active BOOLEAN
);

-- Script to create the 'phone' table
CREATE TABLE phone (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
                       number VARCHAR(255),
                       city_code VARCHAR(10),
                       country_code VARCHAR(10),
                       user_id CHAR(36),
                       FOREIGN KEY (user_id) REFERENCES user(uuid)
);

-- Script to create the 'auth' table
CREATE TABLE auth (
                      uuid CHAR(36) PRIMARY KEY,
                      token VARCHAR(512),
                      hashed_password VARCHAR(255),
                      salt VARCHAR(255),
                      user_id CHAR(36) UNIQUE,
                      last_login TIMESTAMP,
                      FOREIGN KEY (user_id) REFERENCES user(uuid)
);
